version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: [ "27017:27017" ]
    environment:
      MONGO_INITDB_DATABASE: todo_rt
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
